#!/usr/bin/env julia
# Extract VLIDORT shipped reference data into committed Julia data files.
#
# Provenance: PyVLIDORT 2.8.3 distribution at
#   ../PyVLIDORT/src/Components/rtms/RTSI/VLIDORT2p8p3/
#
# Run:  julia --project=. test/vlidort_baseline/extract_references.jl
#
# Re-run only when VLIDORT ships a new distribution. The committed
# reference_data/*.jl files are the source of truth for tests.

const VLIDORT_DIR = abspath(joinpath(@__DIR__, "..", "..", "..", "PyVLIDORT",
                                     "src", "Components", "rtms", "RTSI",
                                     "VLIDORT2p8p3"))
const REF_DIR = joinpath(@__DIR__, "reference_data")
mkpath(REF_DIR)

# ---- Siewert 2000 Problem IIA ------------------------------------------------

"Parse `DATA (PROBLEM_IIA(k,L), L = 0,11)/ ... /` blocks from the Fortran source."
function extract_siewert_greek(fortran_path::AbstractString)
    src = read(fortran_path, String)
    rows = Vector{Vector{Float64}}(undef, 6)
    for k in 1:6
        m = match(Regex("DATA \\(PROBLEM_IIA\\($k,L\\),L = 0,11\\)/(.*?)/", "s"), src)
        m === nothing && error("PROBLEM_IIA row $k not found in $fortran_path")
        body = m.captures[1]
        nums = [parse(Float64, replace(s, r"[Dd]" => "e"))
                for s in eachmatch(r"[-+]?\d+\.\d+(?:[DdEe][-+]?\d+)?", body) |>
                    collect .|> m -> m.match]
        length(nums) == 12 || error("PROBLEM_IIA row $k: expected 12 moments, got $(length(nums))")
        rows[k] = nums
    end
    return rows
end

"Parse fixed-width tables from results_Siewert2000_validation.all.
Each table is 22 rows × (1 cosine + 7 τ-level columns). Returns
`Dict{Int, NamedTuple{(:cosines, :values), Tuple{Vector{Float64}, Matrix{Float64}}}}`."
function extract_siewert_tables(results_path::AbstractString)
    tables = Dict{Int, NamedTuple{(:cosines, :values), Tuple{Vector{Float64}, Matrix{Float64}}}}()
    lines = readlines(results_path)
    current_id = 0
    cosines = Float64[]
    rows = Vector{Vector{Float64}}()
    function flush_current()
        if current_id > 0 && !isempty(cosines)
            mat = reduce(hcat, rows) |> permutedims  # rows × cols
            tables[current_id] = (cosines=copy(cosines), values=mat)
        end
    end
    for raw in lines
        m = match(r"^\s*Table\s+(\d+)\s*$", raw)
        if m !== nothing
            flush_current()
            current_id = parse(Int, m.captures[1])
            empty!(cosines); empty!(rows)
            continue
        end
        nums = [parse(Float64, s.match)
                for s in eachmatch(r"-?\d+\.\d+(?:E[-+]?\d+)?", raw)]
        if !isempty(nums) && current_id > 0
            length(nums) >= 8 || continue   # cosine + 7 τ-levels
            push!(cosines, nums[1])
            push!(rows, nums[2:end])
        end
    end
    flush_current()
    return tables
end

# ---- Emit Julia data files ---------------------------------------------------

function emit_siewert_greek(rows)
    path = joinpath(REF_DIR, "siewert2000_IIA_greek.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: V2p8p3_Siewert2000_validation.f90 PROBLEM_IIA(k, 0:11) DATA blocks.
# DO NOT EDIT BY HAND — re-run extraction.
#
# VLIDORT-to-vSmartMOM mapping (see Fortran lines 280-289):
#   PROBLEM_IIA(1,:) ↔ B[2,2] / α₂ ↔ vSmartMOM α
#   PROBLEM_IIA(2,:) ↔ B[1,1] / α₁ ↔ vSmartMOM β  (phase function)
#   PROBLEM_IIA(3,:) ↔ B[1,2]=B[2,1] / β₁ ↔ vSmartMOM γ
#   PROBLEM_IIA(4,:) ↔ B[4,4] / α₄ ↔ vSmartMOM δ
#   PROBLEM_IIA(5,:) ↔ B[3,4] / β₂ ↔ vSmartMOM −ϵ  (sign flipped! VLIDORT uses
#                                                   GREEKMAT(...,12) = -PROBLEM_IIA(5,:))
#   PROBLEM_IIA(6,:) ↔ B[3,3] / α₃ ↔ vSmartMOM ζ

const SIEWERT_PROBLEM_IIA = (
""")
        labels = (:row1, :row2, :row3, :row4, :row5, :row6)
        for (k, label) in enumerate(labels)
            write(io, "    $label = $(rows[k]),\n")
        end
        write(io, ")\n\n")
        write(io, """
const SIEWERT_α = SIEWERT_PROBLEM_IIA.row1
const SIEWERT_β = SIEWERT_PROBLEM_IIA.row2
const SIEWERT_γ = SIEWERT_PROBLEM_IIA.row3
const SIEWERT_δ = SIEWERT_PROBLEM_IIA.row4
# ϵ stored with sign flip per VLIDORT-to-vSmartMOM B[3,4] convention.
const SIEWERT_ϵ = .-SIEWERT_PROBLEM_IIA.row5
const SIEWERT_ζ = SIEWERT_PROBLEM_IIA.row6
""")
    end
    @info "wrote" path
end

function emit_siewert_tables(tables)
    path = joinpath(REF_DIR, "siewert2000_IIA_truth.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: results_Siewert2000_validation.all (VLIDORT 2.8.3 saved_results).
# DO NOT EDIT BY HAND — re-run extraction.
#
# Each table is 22 rows × 7 columns:
#   rows = μ_view (cosine of viewing zenith, signed; − = upwelling, + = downwelling)
#         (11 upwelling rows for −μ ∈ [−1.0, −0.0], then 11 downwelling rows for +μ ∈ [0.0, 1.0])
#   cols = output τ-levels: [0.0, 0.125, 0.25, 0.5, 0.75, 0.875, 1.0]
#
# Table identification (from Siewert 2000 paper / VLIDORT convention; verified
# empirically by matching magnitudes against a smoke-test vSmartMOM run):
#   Table 2 = I  at relative azimuth 0°
#   Table 3 = Q  at relative azimuth 0°    (U = V = 0 at az=0)
#   Table 4 = I  at relative azimuth 90°
#   Table 5 = Q  at relative azimuth 90°
#   Table 6 = U  at relative azimuth 90°
#   Table 7 = V  at relative azimuth 90°   (small but non-zero)
#   Table 8 = I  at relative azimuth 180°
#   Table 9 = Q  at relative azimuth 180°  (U = V = 0 at az=180)

const SIEWERT_TAU_LEVELS = [0.0, 0.125, 0.25, 0.5, 0.75, 0.875, 1.0]
const SIEWERT_AZIMUTHS_DEG = [0.0, 90.0, 180.0]

""")
        # Sort table IDs.
        for id in sort!(collect(keys(tables)))
            t = tables[id]
            write(io, "const SIEWERT_TABLE$(id)_COSINES = $(t.cosines)\n")
            write(io, "const SIEWERT_TABLE$id = [\n")
            nrow, ncol = size(t.values)
            for i in 1:nrow
                write(io, "    ")
                for j in 1:ncol
                    write(io, repr(t.values[i, j]))
                    j < ncol && write(io, " ")
                end
                i < nrow && write(io, ";")
                write(io, "\n")
            end
            write(io, "]\n\n")
        end
        # Convenience indexed by (az_deg, stokes).
        write(io, """
\"Lookup map (az_deg, stokes_symbol) -> reference matrix (μ_view × τ_level).\"
const SIEWERT_TRUTH = Dict(
    (0.0,   :I) => SIEWERT_TABLE2,
    (0.0,   :Q) => SIEWERT_TABLE3,
    (90.0,  :I) => SIEWERT_TABLE4,
    (90.0,  :Q) => SIEWERT_TABLE5,
    (90.0,  :U) => SIEWERT_TABLE6,
    (90.0,  :V) => SIEWERT_TABLE7,
    (180.0, :I) => SIEWERT_TABLE8,
    (180.0, :Q) => SIEWERT_TABLE9,
)
""")
    end
    @info "wrote" path
end

# ---- solar_tester (scalar) atmosphere + truth -------------------------------

"Parse `vlidort_s_test/input_atmos.dat`. Layout:
  row 1: raymoms[0, n=1..23]   (all 1.0 for Rayleigh L=0)
  row 2: raymoms[1, n=1..23]   (all 0.0 for Rayleigh L=1)
  row 3: raymoms[2, n=1..23]   (Rayleigh L=2 — depol-dependent, here 0.4920)
  rows 4..26: per-layer (n, height_km, molext, molomg, kd1, kd2, kd3, kd4)
Returns a NamedTuple with the parsed fields."
function extract_solar_tester_atmosphere(path::AbstractString)
    lines = readlines(path)
    @assert length(lines) >= 26 "expected ≥26 lines, got $(length(lines))"
    parse_row(line) = [parse(Float64, s) for s in split(line)]
    raymoms = Matrix{Float64}(undef, 3, 23)
    for k in 1:3
        nums = parse_row(lines[k])
        @assert length(nums) == 24 "row $k: expected 24 cols (idx + 23 layers), got $(length(nums))"
        raymoms[k, :] = nums[2:end]
    end
    height_km = Vector{Float64}(undef, 23)
    molext    = Vector{Float64}(undef, 23)
    molomg    = Vector{Float64}(undef, 23)
    for n in 1:23
        nums = parse_row(lines[3 + n])
        @assert length(nums) >= 4 "layer row $n: expected ≥4 cols"
        @assert Int(nums[1]) == n "layer index mismatch at row $(3+n)"
        height_km[n] = nums[2]
        molext[n]    = nums[3]
        molomg[n]    = nums[4]
    end
    return (height_km=height_km, molext=molext, molomg=molomg, raymoms=raymoms)
end

"Parse the STOKES-I block from `results_solar_tester.all`.

Returns a 3-D array `stokes[geom, level, dir, task]` of size
`(36, 5, 2, 6)`, plus the τ-level vector and direction labels.
Direction order: 1=Upwelling, 2=Dnwelling. Task order: 1..6."
function extract_solar_tester_stokes(path::AbstractString;
                                     n_geometries::Int = 36,
                                     n_levels::Int = 5,
                                     n_tasks::Int = 6)
    lines = readlines(path)
    stokes = zeros(Float64, n_geometries, n_levels, 2, n_tasks)
    levels = Float64[]
    re = r"^\s*(\d+)\s+(Upwelling|Dnwelling)\s+@\s*(-?\d+\.\d+)\s+(.+)$"
    for raw in lines
        m = match(re, raw)
        m === nothing && continue
        geom = parse(Int, m.captures[1])
        dir  = m.captures[2] == "Upwelling" ? 1 : 2
        lvl  = parse(Float64, m.captures[3])
        if dir == 1 && geom == 1
            lvl in levels || push!(levels, lvl)
        end
        nums = [parse(Float64, s.match)
                for s in eachmatch(r"-?\d+\.\d+E[-+]?\d+", m.captures[4])]
        length(nums) >= n_tasks || continue
        # find the level index
        ilvl = findfirst(==(lvl), levels)
        ilvl === nothing && (push!(levels, lvl); ilvl = length(levels))
        for t in 1:n_tasks
            stokes[geom, ilvl, dir, t] = nums[t]
        end
    end
    @assert length(levels) == n_levels "expected $n_levels τ-levels, got $(length(levels))"
    return (stokes=stokes, tau_levels=levels)
end

function emit_solar_tester_atmosphere(atmos)
    path = joinpath(REF_DIR, "solar_tester_atmosphere.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: vlidort_s_test/input_atmos.dat (VLIDORT 2.8.3).
# DO NOT EDIT BY HAND — re-run extraction.
#
# 23-layer atmosphere used by V2p8p3_solar_tester.f90.
#   height_km[n] : altitude at layer base (km)        [TOA at 60.0 above layer 1]
#   molext[n]    : layer total optical depth (gas + Rayleigh)
#   molomg[n]    : layer single-scattering albedo (= molsca/molext)
#   raymoms[L+1, n] : Rayleigh phase Legendre coef for L = 0,1,2
#                     (constant across layers; row 3 = 0.4920… ⇒ depol ≈
#                     0.01072 under vSmartMOM's `get_greek_rayleigh`
#                     β[3] = 0.5·(1−δ)/(1+δ/2) convention).
#
# The aerosol layer additions (bottom 6 layers, HG g=0.8, ω=0.95, total τ=0.5)
# are applied in the case file, NOT here — see 2p8p3_solar_tester.f90:280-348.

const SOLAR_TESTER_HEIGHT_KM = $(repr(atmos.height_km))

const SOLAR_TESTER_MOLEXT = $(repr(atmos.molext))

const SOLAR_TESTER_MOLOMG = $(repr(atmos.molomg))

const SOLAR_TESTER_RAYMOMS = [
""")
        for k in 1:3
            write(io, "    ")
            for n in 1:23
                write(io, repr(atmos.raymoms[k, n]))
                n < 23 && write(io, " ")
            end
            k < 3 && write(io, ";")
            write(io, "\n")
        end
        write(io, "]\n")
    end
    @info "wrote" path
end

function emit_solar_tester_truth(stokes, tau_levels)
    path = joinpath(REF_DIR, "solar_tester_truth.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: vlidort_s_test/saved_results/gfortran/results_solar_tester.all
# DO NOT EDIT BY HAND — re-run extraction.
#
# Scalar Stokes-I from VLIDORT solar_tester (NSTOKES=1 in the cfg).
# Layout: SOLAR_TESTER_STOKES[geom, level, dir, task]
#   geom  in 1..36 (lattice: 4 SZA × 3 VZA × 3 RAZ; SZA outer, VZA mid, RAZ inner)
#   level in 1..5  (τ-level; see SOLAR_TESTER_TAU_LEVELS)
#   dir   in 1..2  (1 = Upwelling, 2 = Dnwelling)
#   task  in 1..6  (1=PP-noDM, 2=PP+DM, 3=ReglrPS+DM, 4=EnhncPS+DM, 5,6=variants)
#
# Output values are STOKES (no π factor, unlike the Siewert tables); compare
# directly to vSmartMOM rt_run reflectance (which is L = R = π·I/F₀/π = I in
# the F₀=1 normalization). i.e. modeled = L (no π scaling).
#
# Geometry inputs (from 2p8p3_VLIDORT_ReadInput.cfg, after f90 overrides):
#   SZA (deg)  : [35.0, 67.0, 75.0, 82.0]
#   VZA (deg)  : [10.0, 20.0, 40.0]
#   RAZ (deg)  : [0.0, 90.0, 180.0]
#   Lambertian albedo: 0.05  (f90 driver line 352 overrides cfg's 0.2)

const SOLAR_TESTER_TAU_LEVELS = $(repr(tau_levels))
const SOLAR_TESTER_SZA_DEG    = [35.0, 67.0, 75.0, 82.0]
const SOLAR_TESTER_VZA_DEG    = [10.0, 20.0, 40.0]
const SOLAR_TESTER_RAZ_DEG    = [0.0, 90.0, 180.0]
const SOLAR_TESTER_ALBEDO     = 0.05

const SOLAR_TESTER_DIR_UP = 1
const SOLAR_TESTER_DIR_DN = 2

const SOLAR_TESTER_TASKS = (
    pp_noDM        = 1,    # No FOcorr, no δ-M, plane-parallel
    pp_DM          = 2,    # No FOcorr, with δ-M, plane-parallel
    reglr_ps_DM    = 3,    # FO Regular PS + δ-M
    enhnc_ps_DM    = 4,    # FO Enhanced PS + δ-M
    enhnc_ps_solv  = 5,    # task 4 + Solution Saving
    enhnc_ps_telsc = 6,    # task 5 + BVP Telescoping
)

const SOLAR_TESTER_STOKES = reshape(Float64[
""")
        # Flatten in column-major order matching the reshape below.
        ng, nl, nd, nt = size(stokes)
        for t in 1:nt, d in 1:nd, l in 1:nl, g in 1:ng
            write(io, "    ", repr(stokes[g, l, d, t]),
                  ",  # geom=$g level=$l dir=$d task=$t\n")
        end
        write(io, "], $(ng), $(nl), $(nd), $(nt))\n")
    end
    @info "wrote" path
end

# ---- solar_tester (vector, Stokes-3) — Problem III aerosol ------------------

"Parse `ProblemIII.Moms` (Mie F-matrix expansion, 6 elements per L).
File layout: 5 lines of header/blank/column-header, then rows
`L  a1  b1  a2  a3  b2  a4` starting at line 6. The driver applies a cutoff:
keeps moments while a1 > 1e-6, plus the first below-cutoff moment
(implicit in V2p8p3_solar_tester.f90:294-322). Returns a NamedTuple
with fields `(:a1, :b1, :a2, :a3, :b2, :a4)`, each a vector indexed
L = 0..ngreek_moments_input."
function extract_problemIII_moms(path::AbstractString; cutoff::Float64 = 1.0e-6,
                                  L_max::Int = 106)
    lines = readlines(path)
    columns = (Float64[], Float64[], Float64[], Float64[], Float64[], Float64[])
    lcheck = 0
    L = -1
    # Data rows start at line 6 (after 5 header/blank lines).
    for raw in lines[6:end]
        nums = try
            [parse(Float64, s) for s in split(raw)]
        catch
            continue
        end
        length(nums) == 7 || continue
        amoms = nums[2:end]   # a1, b1, a2, a3, b2, a4
        if abs(amoms[1]) > cutoff
            L += 1
            for k in 1:6
                push!(columns[k], amoms[k])
            end
        else
            lcheck += 1
            if lcheck == 1
                L += 1
                for k in 1:6
                    push!(columns[k], amoms[k])
                end
            end
        end
        (L >= L_max || lcheck >= 2) && break
    end
    return (a1=columns[1], b1=columns[2], a2=columns[3],
            a3=columns[4], b2=columns[5], a4=columns[6])
end

"Parse the multi-block STOKES-{I,Q,U} structure from
`results_solar_tester_IQU0.all`. Each block has the same geom × level ×
direction × task layout as scalar solar_tester. Returns a 4-D array
`stokes[geom, level, dir, task]` per stokes component, packaged in a
Dict keyed by :I, :Q, :U."
function extract_solar_tester_vector_truth(path::AbstractString;
                                            n_geometries::Int = 36,
                                            n_levels::Int = 5,
                                            n_tasks::Int = 6)
    lines = readlines(path)
    out = Dict{Symbol, Array{Float64, 4}}()
    current = nothing
    levels = Float64[]
    block_arr = nothing
    re_block = r"^\s*STOKES-([IQU])"
    re_row = r"^\s*(\d+)\s+(Upwelling|Dnwelling)\s+@\s*(-?\d+\.\d+)\s+(.+)$"
    for raw in lines
        m_block = match(re_block, raw)
        if m_block !== nothing
            sym = Symbol(m_block.captures[1])
            current = sym
            block_arr = zeros(Float64, n_geometries, n_levels, 2, n_tasks)
            empty!(levels)
            out[sym] = block_arr
            continue
        end
        current === nothing && continue
        m_row = match(re_row, raw)
        m_row === nothing && continue
        geom = parse(Int, m_row.captures[1])
        dir  = m_row.captures[2] == "Upwelling" ? 1 : 2
        lvl  = parse(Float64, m_row.captures[3])
        if dir == 1 && geom == 1
            lvl in levels || push!(levels, lvl)
        end
        nums = [parse(Float64, s.match)
                for s in eachmatch(r"-?\d+\.\d+E[-+]?\d+", m_row.captures[4])]
        length(nums) >= n_tasks || continue
        ilvl = findfirst(==(lvl), levels)
        ilvl === nothing && (push!(levels, lvl); ilvl = length(levels))
        for t in 1:n_tasks
            block_arr[geom, ilvl, dir, t] = nums[t]
        end
    end
    return out, levels
end

function emit_problemIII_moms(moms)
    path = joinpath(REF_DIR, "solar_tester_problemIII_aerosol.jl")
    open(path, "w") do io
        L_max = length(moms.a1)
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: vlidort_v_test/ProblemIII.Moms (Mie F-matrix expansion).
# DO NOT EDIT BY HAND — re-run extraction.
#
# Problem III aerosol (gamma-distributed, 0.782 µm, n=1.43, reff=1.05,
# veff=0.07) used by V2p8p3_solar_tester.f90 vector test (NSTOKES=3,
# ω_aer=0.99999, total τ_aer=0.5).
#
# Stored with VLIDORT cutoff already applied: amoms[1] > 1e-6 plus one
# extra below-cutoff moment, matching V2p8p3_solar_tester.f90:294-322.
#
# 6 columns per L correspond to the a1, b1, a2, a3, b2, a4 elements of
# the F-matrix expansion. Mapping to vSmartMOM GreekCoefs:
#     a1 → β  (B[1,1] phase function)
#     b1 → γ  (B[1,2] = B[2,1])
#     a2 → α  (B[2,2])
#     a3 → ζ  (B[3,3])
#     b2 → −ϵ  (B[3,4] sign-flipped per VLIDORT GREEKMAT(.,12) = −b2)
#     a4 → δ  (B[4,4])
# (Same convention as Siewert PROBLEM_IIA.)

const PROBLEMIII_NMOMENTS = $(L_max - 1)   # L = 0..PROBLEMIII_NMOMENTS

const PROBLEMIII_a1 = $(repr(moms.a1))

const PROBLEMIII_b1 = $(repr(moms.b1))

const PROBLEMIII_a2 = $(repr(moms.a2))

const PROBLEMIII_a3 = $(repr(moms.a3))

const PROBLEMIII_b2 = $(repr(moms.b2))

const PROBLEMIII_a4 = $(repr(moms.a4))
""")
    end
    @info "wrote" path
end

function emit_solar_tester_vector_truth(stokes_dict, tau_levels)
    path = joinpath(REF_DIR, "solar_tester_vector_truth.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: vlidort_v_test/saved_results/gfortran/nstokes3/results_solar_tester_IQU0.all
# DO NOT EDIT BY HAND — re-run extraction.
#
# Vector solar_tester geometry differs from scalar solar_tester: the vector
# cfg uses RAZ = [10, 90, 170], not [0, 90, 180]. Three Stokes components
# (I, Q, U) per STOKES-X block in the .all file.
#
# Layout: SOLAR_TESTER_VECTOR_STOKES[:I/:Q/:U][geom, level, dir, task]
#   geom  in 1..36   (4 SZA × 3 VZA × 3 RAZ; SZA outer, VZA mid, RAZ inner)
#   level in 1..5    (τ-level; SOLAR_TESTER_VECTOR_TAU_LEVELS)
#   dir   in 1..2    (1 = Upwelling, 2 = Dnwelling)
#   task  in 1..6    (Tasks 1..6 — only 1..2 are plane-parallel)
#
# Output values are STOKES (no π factor). Direct comparison with vSmartMOM
# rt_run reflectance L = R/F₀ (F₀=1 here).

const SOLAR_TESTER_VECTOR_TAU_LEVELS = $(repr(tau_levels))
const SOLAR_TESTER_VECTOR_SZA_DEG    = [35.0, 67.0, 75.0, 82.0]
const SOLAR_TESTER_VECTOR_VZA_DEG    = [10.0, 20.0, 40.0]
const SOLAR_TESTER_VECTOR_RAZ_DEG    = [10.0, 90.0, 170.0]
const SOLAR_TESTER_VECTOR_ALBEDO     = 0.05

""")
        for sym in (:I, :Q, :U)
            arr = stokes_dict[sym]
            ng, nl, nd, nt = size(arr)
            write(io, "const SOLAR_TESTER_VECTOR_$(sym) = reshape(Float64[\n")
            for t in 1:nt, d in 1:nd, l in 1:nl, g in 1:ng
                write(io, "    ", repr(arr[g, l, d, t]),
                      ",  # geom=$g level=$l dir=$d task=$t\n")
            end
            write(io, "], $(ng), $(nl), $(nd), $(nt))\n\n")
        end
        write(io, """
\"Lookup map (stokes_symbol) -> SOLAR_TESTER_VECTOR_<X> array.\"
const SOLAR_TESTER_VECTOR_STOKES = Dict{Symbol, Array{Float64, 4}}(
    :I => SOLAR_TESTER_VECTOR_I,
    :Q => SOLAR_TESTER_VECTOR_Q,
    :U => SOLAR_TESTER_VECTOR_U,
)
""")
    end
    @info "wrote" path
end

# ---- Driver -----------------------------------------------------------------

function main()
    isdir(VLIDORT_DIR) || error("PyVLIDORT not found at $VLIDORT_DIR")

    @info "extracting Siewert 2000 IIA"
    siewert_src = joinpath(VLIDORT_DIR, "vlidort_v_test", "V2p8p3_Siewert2000_validation.f90")
    siewert_res = joinpath(VLIDORT_DIR, "vlidort_v_test", "saved_results", "gfortran",
                           "results_Siewert2000_validation.all")
    rows = extract_siewert_greek(siewert_src)
    emit_siewert_greek(rows)
    tables = extract_siewert_tables(siewert_res)
    @info "parsed Siewert tables" ids=sort!(collect(keys(tables)))
    emit_siewert_tables(tables)

    @info "extracting solar_tester (scalar)"
    atmos_path = joinpath(VLIDORT_DIR, "vlidort_s_test", "input_atmos.dat")
    truth_path = joinpath(VLIDORT_DIR, "vlidort_s_test", "saved_results", "gfortran",
                          "results_solar_tester.all")
    atmos = extract_solar_tester_atmosphere(atmos_path)
    emit_solar_tester_atmosphere(atmos)
    truth = extract_solar_tester_stokes(truth_path)
    @info "parsed solar_tester truth" tau_levels=truth.tau_levels size=size(truth.stokes)
    emit_solar_tester_truth(truth.stokes, truth.tau_levels)

    @info "extracting solar_tester (vector, Stokes-3)"
    moms_path = joinpath(VLIDORT_DIR, "vlidort_v_test", "ProblemIII.Moms")
    vec_truth_path = joinpath(VLIDORT_DIR, "vlidort_v_test", "saved_results",
                              "gfortran", "nstokes3", "results_solar_tester_IQU0.all")
    moms = extract_problemIII_moms(moms_path)
    @info "parsed Problem III aerosol moments" n=length(moms.a1)
    emit_problemIII_moms(moms)
    vec_truth, vec_levels = extract_solar_tester_vector_truth(vec_truth_path)
    @info "parsed solar_tester vector truth" tau_levels=vec_levels stokes=collect(keys(vec_truth))
    emit_solar_tester_vector_truth(vec_truth, vec_levels)

    @info "done"
end

main()
