#!/usr/bin/env julia
# Extract VLIDORT shipped reference data into committed Julia data files.
#
# Provenance: PyVLIDORT 2.8.3 distribution at
#   ../PyVLIDORT/src/Components/rtms/RTSI/VLIDORT2p8p3/
#
# Run:  julia --project=. test/vlidort_baseline/extract_references.jl
#
# Re-run only when VLIDORT ships a new distribution. The committed
# reference_data/*.jl files are the source of truth for tests.

const VLIDORT_DIR = abspath(joinpath(@__DIR__, "..", "..", "..", "PyVLIDORT",
                                     "src", "Components", "rtms", "RTSI",
                                     "VLIDORT2p8p3"))
const REF_DIR = joinpath(@__DIR__, "reference_data")
mkpath(REF_DIR)

# ---- Siewert 2000 Problem IIA ------------------------------------------------

"Parse `DATA (PROBLEM_IIA(k,L), L = 0,11)/ ... /` blocks from the Fortran source."
function extract_siewert_greek(fortran_path::AbstractString)
    src = read(fortran_path, String)
    rows = Vector{Vector{Float64}}(undef, 6)
    for k in 1:6
        m = match(Regex("DATA \\(PROBLEM_IIA\\($k,L\\),L = 0,11\\)/(.*?)/", "s"), src)
        m === nothing && error("PROBLEM_IIA row $k not found in $fortran_path")
        body = m.captures[1]
        nums = [parse(Float64, replace(s, r"[Dd]" => "e"))
                for s in eachmatch(r"[-+]?\d+\.\d+(?:[DdEe][-+]?\d+)?", body) |>
                    collect .|> m -> m.match]
        length(nums) == 12 || error("PROBLEM_IIA row $k: expected 12 moments, got $(length(nums))")
        rows[k] = nums
    end
    return rows
end

"Parse fixed-width tables from results_Siewert2000_validation.all.
Each table is 22 rows × (1 cosine + 7 τ-level columns). Returns
`Dict{Int, NamedTuple{(:cosines, :values), Tuple{Vector{Float64}, Matrix{Float64}}}}`."
function extract_siewert_tables(results_path::AbstractString)
    tables = Dict{Int, NamedTuple{(:cosines, :values), Tuple{Vector{Float64}, Matrix{Float64}}}}()
    lines = readlines(results_path)
    current_id = 0
    cosines = Float64[]
    rows = Vector{Vector{Float64}}()
    function flush_current()
        if current_id > 0 && !isempty(cosines)
            mat = reduce(hcat, rows) |> permutedims  # rows × cols
            tables[current_id] = (cosines=copy(cosines), values=mat)
        end
    end
    for raw in lines
        m = match(r"^\s*Table\s+(\d+)\s*$", raw)
        if m !== nothing
            flush_current()
            current_id = parse(Int, m.captures[1])
            empty!(cosines); empty!(rows)
            continue
        end
        nums = [parse(Float64, s.match)
                for s in eachmatch(r"-?\d+\.\d+(?:E[-+]?\d+)?", raw)]
        if !isempty(nums) && current_id > 0
            length(nums) >= 8 || continue   # cosine + 7 τ-levels
            push!(cosines, nums[1])
            push!(rows, nums[2:end])
        end
    end
    flush_current()
    return tables
end

# ---- Emit Julia data files ---------------------------------------------------

function emit_siewert_greek(rows)
    path = joinpath(REF_DIR, "siewert2000_IIA_greek.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: V2p8p3_Siewert2000_validation.f90 PROBLEM_IIA(k, 0:11) DATA blocks.
# DO NOT EDIT BY HAND — re-run extraction.
#
# VLIDORT-to-vSmartMOM mapping (see Fortran lines 280-289):
#   PROBLEM_IIA(1,:) ↔ B[2,2] / α₂ ↔ vSmartMOM α
#   PROBLEM_IIA(2,:) ↔ B[1,1] / α₁ ↔ vSmartMOM β  (phase function)
#   PROBLEM_IIA(3,:) ↔ B[1,2]=B[2,1] / β₁ ↔ vSmartMOM γ
#   PROBLEM_IIA(4,:) ↔ B[4,4] / α₄ ↔ vSmartMOM δ
#   PROBLEM_IIA(5,:) ↔ B[3,4] / β₂ ↔ vSmartMOM −ϵ  (sign flipped! VLIDORT uses
#                                                   GREEKMAT(...,12) = -PROBLEM_IIA(5,:))
#   PROBLEM_IIA(6,:) ↔ B[3,3] / α₃ ↔ vSmartMOM ζ

const SIEWERT_PROBLEM_IIA = (
""")
        labels = (:row1, :row2, :row3, :row4, :row5, :row6)
        for (k, label) in enumerate(labels)
            write(io, "    $label = $(rows[k]),\n")
        end
        write(io, ")\n\n")
        write(io, """
const SIEWERT_α = SIEWERT_PROBLEM_IIA.row1
const SIEWERT_β = SIEWERT_PROBLEM_IIA.row2
const SIEWERT_γ = SIEWERT_PROBLEM_IIA.row3
const SIEWERT_δ = SIEWERT_PROBLEM_IIA.row4
# ϵ stored with sign flip per VLIDORT-to-vSmartMOM B[3,4] convention.
const SIEWERT_ϵ = .-SIEWERT_PROBLEM_IIA.row5
const SIEWERT_ζ = SIEWERT_PROBLEM_IIA.row6
""")
    end
    @info "wrote" path
end

function emit_siewert_tables(tables)
    path = joinpath(REF_DIR, "siewert2000_IIA_truth.jl")
    open(path, "w") do io
        write(io, """
# AUTO-GENERATED by extract_references.jl
# Source: results_Siewert2000_validation.all (VLIDORT 2.8.3 saved_results).
# DO NOT EDIT BY HAND — re-run extraction.
#
# Each table is 23 rows × 7 columns:
#   rows = μ_view (cosine of viewing zenith, signed; − = upwelling, + = downwelling)
#   cols = output τ-levels: [0.0, 0.125, 0.25, 0.5, 0.75, 0.875, 1.0]
#
# Table identification (from Siewert 2000 paper / VLIDORT convention; verified
# empirically by matching magnitudes against a smoke-test vSmartMOM run):
#   Table 2 = I  at relative azimuth 0°
#   Table 3 = Q  at relative azimuth 0°    (U = V = 0 at az=0)
#   Table 4 = I  at relative azimuth 90°
#   Table 5 = Q  at relative azimuth 90°
#   Table 6 = U  at relative azimuth 90°
#   Table 7 = V  at relative azimuth 90°   (small but non-zero)
#   Table 8 = I  at relative azimuth 180°
#   Table 9 = Q  at relative azimuth 180°  (U = V = 0 at az=180)

const SIEWERT_TAU_LEVELS = [0.0, 0.125, 0.25, 0.5, 0.75, 0.875, 1.0]
const SIEWERT_AZIMUTHS_DEG = [0.0, 90.0, 180.0]

""")
        # Sort table IDs.
        for id in sort!(collect(keys(tables)))
            t = tables[id]
            write(io, "const SIEWERT_TABLE$(id)_COSINES = $(t.cosines)\n")
            write(io, "const SIEWERT_TABLE$id = [\n")
            nrow, ncol = size(t.values)
            for i in 1:nrow
                write(io, "    ")
                for j in 1:ncol
                    write(io, repr(t.values[i, j]))
                    j < ncol && write(io, " ")
                end
                i < nrow && write(io, ";")
                write(io, "\n")
            end
            write(io, "]\n\n")
        end
        # Convenience indexed by (az_deg, stokes).
        write(io, """
\"Lookup map (az_deg, stokes_symbol) -> reference matrix (μ_view × τ_level).\"
const SIEWERT_TRUTH = Dict(
    (0.0,   :I) => SIEWERT_TABLE2,
    (0.0,   :Q) => SIEWERT_TABLE3,
    (90.0,  :I) => SIEWERT_TABLE4,
    (90.0,  :Q) => SIEWERT_TABLE5,
    (90.0,  :U) => SIEWERT_TABLE6,
    (90.0,  :V) => SIEWERT_TABLE7,
    (180.0, :I) => SIEWERT_TABLE8,
    (180.0, :Q) => SIEWERT_TABLE9,
)
""")
    end
    @info "wrote" path
end

# ---- Driver -----------------------------------------------------------------

function main()
    isdir(VLIDORT_DIR) || error("PyVLIDORT not found at $VLIDORT_DIR")
    siewert_src = joinpath(VLIDORT_DIR, "vlidort_v_test", "V2p8p3_Siewert2000_validation.f90")
    siewert_res = joinpath(VLIDORT_DIR, "vlidort_v_test", "saved_results", "gfortran",
                           "results_Siewert2000_validation.all")
    @info "extracting Siewert 2000 IIA"
    rows = extract_siewert_greek(siewert_src)
    emit_siewert_greek(rows)
    tables = extract_siewert_tables(siewert_res)
    @info "parsed tables" ids=sort!(collect(keys(tables)))
    emit_siewert_tables(tables)
    @info "done"
end

main()
