# AUTO-GENERATED by extract_references.jl
# Source: V2p8p3_Siewert2000_validation.f90 PROBLEM_IIA(k, 0:11) DATA blocks.
# DO NOT EDIT BY HAND — re-run extraction.
#
# VLIDORT-to-vSmartMOM mapping (see Fortran lines 280-289):
#   PROBLEM_IIA(1,:) ↔ B[2,2] / α₂ ↔ vSmartMOM α
#   PROBLEM_IIA(2,:) ↔ B[1,1] / α₁ ↔ vSmartMOM β  (phase function)
#   PROBLEM_IIA(3,:) ↔ B[1,2]=B[2,1] / β₁ ↔ vSmartMOM −γ  (sign flipped: VLIDORT
#                                                          stores Mishchenko-style
#                                                          γ; vSmartMOM uses
#                                                          Hovenier convention)
#   PROBLEM_IIA(4,:) ↔ B[4,4] / α₄ ↔ vSmartMOM δ
#   PROBLEM_IIA(5,:) ↔ B[3,4] / β₂ ↔ vSmartMOM −ϵ  (sign flipped! VLIDORT uses
#                                                   GREEKMAT(...,12) = -PROBLEM_IIA(5,:))
#   PROBLEM_IIA(6,:) ↔ B[3,3] / α₃ ↔ vSmartMOM ζ
#
# WHY γ SIGN-FLIPS ON IMPORT: vSmartMOM's `get_greek_rayleigh` returns
# γ[L=2] = +√(3/2)·dpl_p (Hovenier convention, matching
# `compute_NAI2.jl:132` f₁₂ = −Re(|s1|²−|s2|²)). VLIDORT stores γ with
# the opposite sign. Importing the data file as-is would mix Hovenier
# (Rayleigh) with Mishchenko (aerosol) γ in mixed-layer atmospheres
# (e.g. Case C) and produce sign-clashed Z[1,2]. We sign-flip on
# import so all γ inside vSmartMOM is Hovenier; the price is that
# truth Q/U/V from VLIDORT must also be sign-flipped at the comparison
# stage. See dev_notes/case_c_q_u_conventions.md.

const SIEWERT_PROBLEM_IIA = (
    row1 = [0.0, 0.0, 3.726079, 2.202868, 1.190694, 0.391203, 0.105556, 0.020484, 0.003097, 0.000366, 3.5e-5, 3.0e-6],
    row2 = [1.0, 2.104031, 2.095158, 1.414939, 0.703593, 0.235001, 0.064039, 0.012837, 0.00201, 0.000246, 2.4e-5, 2.0e-6],
    row3 = [0.0, 0.0, -0.116688, -0.20937, -0.227137, -0.144524, -0.05264, -0.0124, -0.002093, -0.000267, -2.7e-5, -2.0e-6],
    row4 = [0.915207, 2.095727, 2.008624, 1.436545, 0.706244, 0.238475, 0.056448, 0.009703, 0.001267, 0.00013, 1.1e-5, 1.0e-6],
    row5 = [0.0, 0.0, 0.065456, 0.221658, 0.097752, 0.052458, 0.009239, 0.001411, 0.000133, 1.1e-5, 1.0e-6, 0.0],
    row6 = [0.0, 0.0, 3.615946, 2.240516, 1.139473, 0.365605, 0.082779, 0.013649, 0.001721, 0.000172, 1.4e-5, 1.0e-6],
)

const SIEWERT_α = SIEWERT_PROBLEM_IIA.row1
const SIEWERT_β = SIEWERT_PROBLEM_IIA.row2
# γ stored with sign flip per VLIDORT(Mishchenko)→vSmartMOM(Hovenier) convention.
const SIEWERT_γ = .-SIEWERT_PROBLEM_IIA.row3
const SIEWERT_δ = SIEWERT_PROBLEM_IIA.row4
# ϵ stored with sign flip per VLIDORT-to-vSmartMOM B[3,4] convention.
const SIEWERT_ϵ = .-SIEWERT_PROBLEM_IIA.row5
const SIEWERT_ζ = SIEWERT_PROBLEM_IIA.row6
