# AUTO-GENERATED by extract_references.jl
# Source: vlidort_s_test/input_atmos.dat (VLIDORT 2.8.3).
# DO NOT EDIT BY HAND — re-run extraction.
#
# 23-layer atmosphere used by V2p8p3_solar_tester.f90.
#   height_km[n] : altitude at layer base (km)        [TOA at 60.0 above layer 1]
#   molext[n]    : layer total optical depth (gas + Rayleigh)
#   molomg[n]    : layer single-scattering albedo (= molsca/molext)
#   raymoms[L+1, n] : Rayleigh phase Legendre coef for L = 0,1,2
#                     (constant across layers; row 3 = 0.4920… ⇒ depol ≈
#                     0.01072 under vSmartMOM's `get_greek_rayleigh`
#                     β[3] = 0.5·(1−δ)/(1+δ/2) convention).
#
# The aerosol layer additions (bottom 6 layers, HG g=0.8, ω=0.95, total τ=0.5)
# are applied in the case file, NOT here — see 2p8p3_solar_tester.f90:280-348.

const SOLAR_TESTER_HEIGHT_KM = [50.0, 40.0, 35.0, 30.0, 27.0, 24.0, 22.0, 20.0, 18.0, 16.0, 14.0, 12.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.0]

const SOLAR_TESTER_MOLEXT = [0.00095538395, 0.0058462352, 0.0081316647, 0.01672586, 0.016468887, 0.023289245, 0.019245881, 0.02168458, 0.024326921, 0.02836878, 0.035447615, 0.046711682, 0.06179488, 0.037303793, 0.042035878, 0.047250724, 0.052956122, 0.059159265, 0.065885524, 0.073175455, 0.081044697, 0.089464827, 0.098444144]

const SOLAR_TESTER_MOLOMG = [0.58336348, 0.35850557, 0.31990731, 0.33564175, 0.36325497, 0.4104551, 0.48396851, 0.59130546, 0.72339743, 0.84872679, 0.92966229, 0.9658676, 0.98109016, 0.98628527, 0.98671205, 0.9862942, 0.98573852, 0.98542528, 0.98544897, 0.98560228, 0.9860764, 0.98749306, 0.98968253]

const SOLAR_TESTER_RAYMOMS = [
    1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0;
    0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0;
    0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061 0.4920062061
]
